#!/usr/bin/env bash
set -euo pipefail

# ⚠️ This script is experimental and not officially supported - Use at your own risk.
#
# Install live version:
#
# $ install -m 0755 <(curl https://raw.githubusercontent.com/johnmarcou/monadctl/refs/heads/main/run-monadctl.sh) /usr/local/bin/monadctl
#

CONFIG_FILE="/home/monad/monad-bft/config/node.toml"
DEFAULT_NETWORK="mainnet"

usage() {
  cat <<EOF
monadctl – minimal control tool

Usage:
  monadctl config          # print node configuration
  monadctl edit            # edit node configuration
  monadctl flush           # clear workspace, database and logs
  monadctl init            # initialise node configuration
  monadctl reload          # reload monad configuration
  monadctl reset           # reset the node
  monadctl reset --hard    # reset the node and import latest snapshot
  monadctl restart         # restart monad services
  monadctl start           # start monad services
  monadctl status          # show node status
  monadctl stop            # stop monad services
EOF
}

main() {
  case "${1:-}" in
  init)
    shift
    cmd_init "$@"
    ;;
  status)
    shift
    cmd_status "$@"
    ;;
  reset)
    shift
    cmd_reset "$@"
    ;;
  start) cmd_start ;;
  flush) cmd_flush ;;
  stop) cmd_stop ;;
  restart) cmd_restart ;;
  reload) cmd_reload ;;
  edit) cmd_edit ;;
  config) cmd_config ;;
  *) usage ;;
  esac
}

cmd_config() {
  cat "$CONFIG_FILE"
}

cmd_edit() {
  exec "${EDITOR:-vi}" $CONFIG_FILE </dev/tty >/dev/tty 2>&1
}

cmd_status() {
  bash <(curl -fsSL "https://bucket.monadinfra.com/scripts/monad-status.sh") "$@"
}

cmd_start() {
  systemctl start monad-bft monad-execution monad-rpc
}

cmd_stop() {
  systemctl stop monad-bft monad-execution monad-rpc
}

cmd_flush() {
  cmd_stop
  bash /opt/monad/scripts/reset-workspace.sh
  journalctl --rotate && journalctl --vacuum-time=1s
}

cmd_restart() {
  cmd_stop && sleep 2 && cmd_start
}

cmd_reload() {
  monad-debug-node -c /home/monad/monad-bft/controlpanel.sock reload-config
}

cmd_reset() {
  local hard=false

  while [[ $# -gt 0 ]]; do
    case "$1" in
    --hard)
      hard=true
      shift
      ;;
    -*)
      echo "Unknown option for reset: $1" >&2
      exit 1
      ;;
    *)
      break
      ;;
    esac
  done

  if $hard; then
    cmd_hard_reset
  else
    cmd_soft_reset
  fi
}

cmd_soft_reset() {
  cmd_stop

  NETWORK=$(grep -Po '^network_name\s*=\s*"?\K[^"#]+' $CONFIG_FILE)
  MF_BUCKET=https://bucket.monadinfra.com
  VALIDATORS_FILE=/home/monad/monad-bft/config/validators/validators.toml

  curl -sSL "$MF_BUCKET/scripts/$NETWORK/download-forkpoint.sh" | bash
  curl "$MF_BUCKET/validators/$NETWORK/validators.toml" -o $VALIDATORS_FILE
  chown monad:monad $VALIDATORS_FILE

  cmd_start
}

cmd_hard_reset() {
  cmd_stop

  NETWORK=$(grep -Po '^network_name\s*=\s*"?\K[^"#]+' $CONFIG_FILE)
  MF_BUCKET="https://bucket.monadinfra.com"

  bash /opt/monad/scripts/reset-workspace.sh
  curl -fsSL "${MF_BUCKET}/scripts/${NETWORK}/restore-from-snapshot.sh" | bash

  cmd_start
}

cmd_init() {
  set -x
  NETWORK=${1:-$DEFAULT_NETWORK}
  DISK=${2:-nvme1n1}

  systemctl stop monad-bft monad-execution monad-rpc || true

  apt upgrade -y || true
  apt install -y curl nvme-cli aria2 jq
  cat <<EOF >/etc/apt/sources.list.d/category-labs.sources
Types: deb
URIs: https://pkg.category.xyz/
Suites: noble
Components: main
Signed-By: /etc/apt/keyrings/category-labs.gpg
EOF

  curl -fsSL https://pkg.category.xyz/keys/public-key.asc |
    gpg --dearmor --yes -o /etc/apt/keyrings/category-labs.gpg

  apt update && apt install -y monad
  useradd -m -s /bin/bash monad || true
  mkdir -p /home/monad/monad-bft/config \
    /home/monad/monad-bft/ledger \
    /home/monad/monad-bft/config/forkpoint \
    /home/monad/monad-bft/config/validators

  TRIEDB_DRIVE="/dev/$DISK"
  parted -s $TRIEDB_DRIVE mklabel gpt
  parted -s $TRIEDB_DRIVE mkpart triedb 0% 100%
  sleep 1
  PARTUUID=$(lsblk -o PARTUUID $TRIEDB_DRIVE | tail -n 1)
  echo "Disk PartUUID: ${PARTUUID}"
  echo "ENV{ID_PART_ENTRY_UUID}==\"$PARTUUID\", MODE=\"0666\", SYMLINK+=\"triedb\"" |
    tee /etc/udev/rules.d/99-triedb.rules
  sleep 2
  udevadm trigger
  sleep 2
  udevadm control --reload
  sleep 2
  udevadm settle
  sleep 2
  ls -l /dev/triedb

  monad-mpt --storage /dev/triedb --create

  ufw allow ssh
  ufw allow 8000
  ufw --force enable

  OTEL_VERSION="0.139.0"
  OTEL_PACKAGE="https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v${OTEL_VERSION}/otelcol_${OTEL_VERSION}_linux_amd64.deb"
  curl -fsSL "$OTEL_PACKAGE" -o /tmp/otelcol_linux_amd64.deb
  dpkg -i /tmp/otelcol_linux_amd64.deb
  cp /opt/monad/scripts/otel-config.yaml /etc/otelcol/config.yaml
  systemctl restart otelcol

  MF_BUCKET=https://bucket.monadinfra.com
  curl -o /home/monad/.env $MF_BUCKET/config/${NETWORK}/latest/.env.example
  curl -o /home/monad/monad-bft/config/node.toml $MF_BUCKET/config/${NETWORK}/latest/full-node-node.toml

  sed -i "s|^KEYSTORE_PASSWORD=$|KEYSTORE_PASSWORD='$(openssl rand -base64 32)'|" /home/monad/.env
  source /home/monad/.env
  mkdir -p /opt/monad/backup/
  echo "Keystore password: ${KEYSTORE_PASSWORD}" >/opt/monad/backup/keystore-password-backup

  rm /home/monad/monad-bft/config/id-secp || true
  rm /home/monad/monad-bft/config/id-bls || true

  monad-keystore create \
    --key-type secp \
    --keystore-path /home/monad/monad-bft/config/id-secp \
    --password "${KEYSTORE_PASSWORD}" >/opt/monad/backup/secp-backup

  monad-keystore create \
    --key-type bls \
    --keystore-path /home/monad/monad-bft/config/id-bls \
    --password "${KEYSTORE_PASSWORD}" >/opt/monad/backup/bls-backup

  grep "public key" /opt/monad/backup/secp-backup /opt/monad/backup/bls-backup |
    tee /home/monad/pubkey-secp-bls

  source /home/monad/.env
  sig_out="$(
    monad-sign-name-record \
      --address "$(curl -s4 ifconfig.me)":8000 \
      --keystore-path /home/monad/monad-bft/config/id-secp \
      --password "${KEYSTORE_PASSWORD}" \
      --self-record-seq-num 0
  )"

  node_name_val="$(hostname)"
  self_address=$(printf '%s\n' "$sig_out" | grep '^self_address' | cut -d'"' -f2)
  self_record_seq_num=$(printf '%s\n' "$sig_out" | grep '^self_record_seq_num' | awk '{print $3}')
  self_name_record_sig=$(printf '%s\n' "$sig_out" | grep '^self_name_record_sig' | cut -d'"' -f2)

  sed -i \
    -e "s|^node_name = \".*\"|node_name = \"$node_name_val\"|" \
    -e "s|^self_address = \".*\"|self_address = \"$self_address\"|" \
    -e "s|^self_record_seq_num = .*|self_record_seq_num = $self_record_seq_num|" \
    -e "s|^self_name_record_sig = \".*\"|self_name_record_sig = \"$self_name_record_sig\"|" \
    /home/monad/monad-bft/config/node.toml

  chown -R monad:monad /home/monad/
  systemctl enable monad-bft monad-execution monad-rpc

}

main "$@"
