volumes:
  shared-data:

networks:
  solonet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:

  validator-1:
    container_name: validator-1
    networks:
      solonet:
        ipv4_address: 172.21.0.11
    build: .
    privileged: true
    ports:
      - 8080:8080
      - 8081:8080
    environment:
      VAL_ID: 1
      TOTAL_VALIDATOR_NUMBER: 4
    volumes:
      - shared-data:/shared

  validator-2:
    container_name: validator-2
    networks:
      solonet:
        ipv4_address: 172.21.0.12
    build: .
    privileged: true
    ports:
      - 8082:8080
    environment:
      VAL_ID: 2
      TOTAL_VALIDATOR_NUMBER: 4
    volumes:
      - shared-data:/shared

  validator-3:
    container_name: validator-3
    networks:
      solonet:
        ipv4_address: 172.21.0.13
    build: .
    privileged: true
    ports:
      - 8083:8080
    environment:
      VAL_ID: 3
      TOTAL_VALIDATOR_NUMBER: 4
    volumes:
      - shared-data:/shared

  validator-4:
    container_name: validator-4
    networks:
      solonet:
        ipv4_address: 172.21.0.14
    build: .
    privileged: true
    ports:
      - 8084:8080
    environment:
      VAL_ID: 4
      TOTAL_VALIDATOR_NUMBER: 4
    volumes:
      - shared-data:/shared
